FROM rust:latest as builder

WORKDIR /app

COPY . .

RUN cargo build --release -p updater
RUN cargo build --release -p server

FROM ubuntu:22.04

WORKDIR /app

COPY --from=builder /app/target/release/updater .
COPY --from=builder /app/target/release/server .
COPY config/ ./config/
RUN chmod +x updater server

CMD ["bash"]