version: "3.8"

services:
  updater:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./update_server_keys"]
    volumes:
      - ./config:/app/config
    # Once updater finishes, config/config.toml is updated on host

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - updater
    command: ["./server"]
    volumes:
      - ./config:/app/config
    ports:
      - "8080:3333"

  client1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - updater
      - server
    command: ["./tui"]
    volumes:
      - ./config:/app/config

  client2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - updater
      - server
    command: ["./tui"]
    volumes:
      - ./config:/app/config
