server_ip = "127.0.0.1"
server_port = "3333"
private_key_server = "keKCIWKBrJl6ffles39JCCp0oR71Ej48C2db6Fvgqio="
public_key_server = "4iWjElTGS+8qsJ94IZdXuaFIFpyReA8mu3csi8r0C38="
log_level = "debug"
