[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayref = "0.3.9"
base64 = "0.22.1"
chrono = "0.4.39"
log = "0.4.25"
protocol = { path = "../protocol" }
serde_json = "1.0.137"
